In [1]:
import numpy as np
import pandas as pd
import sys
import os

import interClusLib
from interClusLib.IntervalData import IntervalData
from interClusLib.metric import *
from interClusLib.clustering.IntervalKMeans import IntervalKMeans
from interClusLib.visualization.HeatMap import HeatMap
from interClusLib.visualization.Interval2d import Interval2d
from interClusLib.visualization.Interval3d import Interval3d
from interClusLib.visualization.IntervalParallelCoordinates import IntervalParallelCoordinates

In [3]:
data = IntervalData.from_csv("ModifiedChinaTemp.csv")

print(data.get_intervals())

feature_T1_lower    13
feature_T1_upper    10
feature_T2_lower    13
feature_T2_upper    13
feature_T3_lower    13
feature_T3_upper    10
feature_T4_lower     7
feature_T4_upper     6
dtype: int64
[[[  0.67  14.83]
  [ 13.44  28.46]
  [ 31.18  19.82]
  [  9.98    nan]]

 [[ 14.38   2.32]
  [ 28.47    nan]
  [ 23.19  32.31]
  [  1.01  10.99]]

 [[  0.91  12.49]
  [ 28.4   11.8 ]
  [ 19.68  34.12]
  [  2.99  10.31]]

 [[ -1.98  15.48]
  [ 14.5   28.1 ]
  [ 20.81    nan]
  [  4.89  11.91]]

 [[   nan  13.27]
  [ 12.81  29.09]
  [ 20.58    nan]
  [  3.61  13.19]]

 [[  1.43  14.37]
  [   nan  30.64]
  [ 19.72  32.78]
  [ 11.49   4.61]]

 [[  1.19  10.31]
  [ 11.38  29.02]
  [ 19.19  31.01]
  [  2.3   10.8 ]]

 [[   nan  15.02]
  [   nan  30.51]
  [ 19.88  32.82]
  [  1.69  10.11]]

 [[  1.63  13.57]
  [ 11.99  28.11]
  [   nan  31.4 ]
  [  1.9    9.9 ]]

 [[ 13.48    nan]
  [ 13.03  27.77]
  [ 22.18    nan]
  [ 10.09   3.21]]

 [[ -1.38  14.58]
  [ 12.12    nan]
  [ 20.07  32.63]
  [  1.99